package com.ProtocolDemo.demo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

public final class HelloWorldOuterClass {
  private HelloWorldOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloWorldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HelloWorld)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string helloWorld = 1;</code>
     * @return Whether the helloWorld field is set.
     */
    boolean hasHelloWorld();
    /**
     * <code>required string helloWorld = 1;</code>
     * @return The helloWorld.
     */
    java.lang.String getHelloWorld();
    /**
     * <code>required string helloWorld = 1;</code>
     * @return The bytes for helloWorld.
     */
    com.google.protobuf.ByteString
        getHelloWorldBytes();
  }
  /**
   * Protobuf type {@code HelloWorld}
   */
  public static final class HelloWorld extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HelloWorld)
      HelloWorldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloWorld.newBuilder() to construct.
    private HelloWorld(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloWorld() {
      helloWorld_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HelloWorld();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloWorld(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              helloWorld_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldOuterClass.internal_static_HelloWorld_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldOuterClass.internal_static_HelloWorld_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HelloWorldOuterClass.HelloWorld.class, HelloWorldOuterClass.HelloWorld.Builder.class);
    }

    private int bitField0_;
    public static final int HELLOWORLD_FIELD_NUMBER = 1;
    private volatile java.lang.Object helloWorld_;
    /**
     * <code>required string helloWorld = 1;</code>
     * @return Whether the helloWorld field is set.
     */
    @java.lang.Override
    public boolean hasHelloWorld() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string helloWorld = 1;</code>
     * @return The helloWorld.
     */
    @java.lang.Override
    public java.lang.String getHelloWorld() {
      java.lang.Object ref = helloWorld_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          helloWorld_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string helloWorld = 1;</code>
     * @return The bytes for helloWorld.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHelloWorldBytes() {
      java.lang.Object ref = helloWorld_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        helloWorld_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHelloWorld()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, helloWorld_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, helloWorld_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HelloWorldOuterClass.HelloWorld)) {
        return super.equals(obj);
      }
      HelloWorldOuterClass.HelloWorld other = (HelloWorldOuterClass.HelloWorld) obj;

      if (hasHelloWorld() != other.hasHelloWorld()) return false;
      if (hasHelloWorld()) {
        if (!getHelloWorld()
            .equals(other.getHelloWorld())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHelloWorld()) {
        hash = (37 * hash) + HELLOWORLD_FIELD_NUMBER;
        hash = (53 * hash) + getHelloWorld().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HelloWorldOuterClass.HelloWorld parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HelloWorldOuterClass.HelloWorld parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HelloWorldOuterClass.HelloWorld parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HelloWorldOuterClass.HelloWorld parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HelloWorldOuterClass.HelloWorld parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HelloWorldOuterClass.HelloWorld parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HelloWorldOuterClass.HelloWorld parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HelloWorldOuterClass.HelloWorld parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HelloWorldOuterClass.HelloWorld parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HelloWorldOuterClass.HelloWorld parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HelloWorldOuterClass.HelloWorld parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HelloWorldOuterClass.HelloWorld parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HelloWorldOuterClass.HelloWorld prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HelloWorld}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HelloWorld)
        HelloWorldOuterClass.HelloWorldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HelloWorldOuterClass.internal_static_HelloWorld_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HelloWorldOuterClass.internal_static_HelloWorld_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HelloWorldOuterClass.HelloWorld.class, HelloWorldOuterClass.HelloWorld.Builder.class);
      }

      // Construct using com.ProtocolDemo.demo.HelloWorldOuterClass.HelloWorld.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        helloWorld_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HelloWorldOuterClass.internal_static_HelloWorld_descriptor;
      }

      @java.lang.Override
      public HelloWorldOuterClass.HelloWorld getDefaultInstanceForType() {
        return HelloWorldOuterClass.HelloWorld.getDefaultInstance();
      }

      @java.lang.Override
      public HelloWorldOuterClass.HelloWorld build() {
        HelloWorldOuterClass.HelloWorld result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public HelloWorldOuterClass.HelloWorld buildPartial() {
        HelloWorldOuterClass.HelloWorld result = new HelloWorldOuterClass.HelloWorld(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.helloWorld_ = helloWorld_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HelloWorldOuterClass.HelloWorld) {
          return mergeFrom((HelloWorldOuterClass.HelloWorld)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HelloWorldOuterClass.HelloWorld other) {
        if (other == HelloWorldOuterClass.HelloWorld.getDefaultInstance()) return this;
        if (other.hasHelloWorld()) {
          bitField0_ |= 0x00000001;
          helloWorld_ = other.helloWorld_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasHelloWorld()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HelloWorldOuterClass.HelloWorld parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HelloWorldOuterClass.HelloWorld) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object helloWorld_ = "";
      /**
       * <code>required string helloWorld = 1;</code>
       * @return Whether the helloWorld field is set.
       */
      public boolean hasHelloWorld() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string helloWorld = 1;</code>
       * @return The helloWorld.
       */
      public java.lang.String getHelloWorld() {
        java.lang.Object ref = helloWorld_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            helloWorld_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string helloWorld = 1;</code>
       * @return The bytes for helloWorld.
       */
      public com.google.protobuf.ByteString
          getHelloWorldBytes() {
        java.lang.Object ref = helloWorld_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          helloWorld_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string helloWorld = 1;</code>
       * @param value The helloWorld to set.
       * @return This builder for chaining.
       */
      public Builder setHelloWorld(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        helloWorld_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string helloWorld = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHelloWorld() {
        bitField0_ = (bitField0_ & ~0x00000001);
        helloWorld_ = getDefaultInstance().getHelloWorld();
        onChanged();
        return this;
      }
      /**
       * <code>required string helloWorld = 1;</code>
       * @param value The bytes for helloWorld to set.
       * @return This builder for chaining.
       */
      public Builder setHelloWorldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        helloWorld_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HelloWorld)
    }

    // @@protoc_insertion_point(class_scope:HelloWorld)
    private static final HelloWorldOuterClass.HelloWorld DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HelloWorldOuterClass.HelloWorld();
    }

    public static HelloWorldOuterClass.HelloWorld getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HelloWorld>
        PARSER = new com.google.protobuf.AbstractParser<HelloWorld>() {
      @java.lang.Override
      public HelloWorld parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloWorld(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloWorld> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloWorld> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public HelloWorldOuterClass.HelloWorld getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloWorld_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloWorld_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020HelloWorld.proto\" \n\nHelloWorld\022\022\n\nhell" +
      "oWorld\030\001 \002(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HelloWorld_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloWorld_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloWorld_descriptor,
        new java.lang.String[] { "HelloWorld", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
